modLoader="javafml"
loaderVersion="[47,)"
license="MIT License"

[[mods]]
modId="stellar_explorer"
version="0.0.1"
displayName="Stellar Explorer"
displayURL="https://mcreator.net"
credits="have fun^^"
authors="Snow(^^"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.stellar_explorer]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration